name: Spell-check and build

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Instal dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          aspell \
          aspell-pt-br
    - uses: actions/checkout@v4
    - name: check syntax
      run: |
        files=$(ls conteudo/ | grep .tex)
        for f in $files; do
          echo "=== Checking $f ==="
          cat conteudo/$f | aspell list lang pt_Br -a -t --home-dir=$(pwd) --personal=allowed-words.txt
        done
